### PR TITLE
add set and get config

### PR DESCRIPTION
**Pull request by bxdoan**
Add set and get the config
Update README for how to update URL and key pair

### CODE REVIEW

**Comment by imduchuyyy** [comment]
Thanks for contribute !!!.
I have new idea for Tartarus wallet, something like `solana-cli`.

**Comment by imduchuyyy** [comment]
LGTM

**Comment by bxdoan** [comment]
Why did you remove transfer_eth/token function? Can you bring it back?
It's useful wallet

**Comment by imduchuyyy** [comment]
Ah, In last 3 months, I deiced to re-struct my project. Unfortunately, I wasn't have time to do this. I will bring `transfer feature` back in the future with new version.

**Comment by imduchuyyy** [comment]
Research about tornado cash for adapt with tartarus wallet took me so many time.

**Pull request merged**
