### PR TITLE
Bring back transfer

### PR DESCRIPTION
**Pull request by bxdoan**
bing back transfer

### CODE REVIEW

**Comment by bxdoan** [comment]
Hi @bui-duc-huy , lets me help you bring back the transfer, you can upgrade tornado cash later

**Comment by imduchuyyy** [comment]
Hi @bxdoan, many thanks for help, I just split some service and follow OOP modal, check it out.

**Comment by imduchuyyy** [comment]
`token.py` will handle every action such as `get_balance`, `get_transfer_transaction` or something like this. On the other hand, `wallet.py` will handle `create_wallet`, `sign_transaction`, `send_transaction` etc.

**Comment by bxdoan** [comment]
got it, nice structure

**Comment by imduchuyyy** [comment]
Many thanks, maybe this PR should be closed. Wait for the transfer function!!

**Pull request closed without merging**
